language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install lxml coverage codecov
script: coverage setup.py test
after_script: codecov
matrix:
  allow_failures:
  - python: 3.5
  - python: 3.6

